language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x ./gradlew

notifications:
  email:
    recipients:
      - twoye1193@ajou.ac.kr

before_deploy: # deploy 명령어가 실행되기 전에 수행
  - zip -r you-and-i-backend * # 현재 경로의 모든 파일을 todo-app-backend.zip 파일로 압축
  - mkdir -p deploy
  - mv you-and-i-backend.zip deploy/you-and-i-backend.zip

deploy: # 외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis CI의 Repository Environment Variable 설정 값
    secret_access_key: $AWS_SECRET_KEY # Travis CI의 Repository Environment Variable 설정 값
    bucket: you-and-i-backend-build # S3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true